### PR TITLE
Update to fetch version with --branch bug fix

### PR DESCRIPTION
**Pull request by brikis98**
Pick up the fix from https://github.com/gruntwork-io/fetch/issues/87, released in https://github.com/gruntwork-io/fetch/releases/tag/v0.3.14.

### CODE REVIEW

**Review by zackproser — APPROVED** [review]
LGTM

**Review by robmorgan — APPROVED** [review]
LGTM

**Comment by brikis98** [comment]
Thanks for the reviews! Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/gruntwork-installer/releases/tag/v0.0.33

**Pull request merged**
